### ISSUE TITLE
Syntax colors

### ISSUE THREAD

**Issue by JCBerger** [jwillinghalpern/filemaker-vscode-bundle#11] opened 2022-07-20 01:08 UTC
I'm not sure if this is better suited for a "discussion" or as an "issue," but I decided to take this route so that you can ignore the issue in case you just want to. I imagine that use case is probably extremely narrow, but I've been teaching myself Cypher and how to use Neo4j to make graph databases. 

I would still consider my uses of Neo4j to fall into the category of "bumbling around," and because I'm more familiar with Filemaker at this point, I have used that as my foundation to format and prepare queries in Cypher to go into Neo4j, that way I can (hopefully) cut down on the errors and speed up input during data entry. What I've done is to create a calculated field that puts out a query that can be copied and pasted into Neo4j. Unfortunately, because I'm concatenating so many fields, even Filemaker's [support document](https://support.claris.com/s/answerview?anum=5038&language=en_US) begins to lose its utility as my eyes glaze over all of the back(forward?) slashes. (Oh, and part of the Cypher query requires the use of quotation marks and apostrophes... which is why it's such a PITA.)

As an example, here is one calculated field:
`"CREATE (" & Node_Name & Node_type & " {name: \"" & Name & "\", first_name: \"" & First_name & "\",  middle_name: \"" & Middle_name & "\", last_name: \"" & Last_name & "\", suffix: '" & Suffix & "', nickname: '" & Nickname & "', formal_name: '" & Formal_Name & "', racing_number: '" & Racing_number & "', gender: '" & Gender & "', born: \"" & Date_of_birth & "\", died: \"" & Date_of_death & "\", nationality: '" & Nationality & "', country: \"" & Country & "\", address_latitude: \"" & address_latitude & "\", address_longitude: \"" & address_longitude & "\", public_figure: '" & Public_figure & "', node_tags: \"" & node_tags & "\", " & Node_properties & "sources_for_information: \"" & Sources_for_information & "\", filemaker_node_id: '" & Unique_FileMaker_node_ID & "'})"`

The question/issue I have, is when I use your extension in VS Code, I see two shades of red (I would attach a screenshot if I could), and the shades seem to be appearing inconsistently (between text intended for Filemaker versus literal text that would be concatenated). Is there a way to tell what the colors indicate in your extension?

P.s. To be clear, the inconsistency could be the result of my own error, as I adding new fields and running into errors.

**Comment by jwillinghalpern** [comment] 2022-07-20 02:07
Thanks for your comment.

<img width="619" alt="Screen Shot 2022-07-19 at 7 06 02 PM" src="https://user-images.githubusercontent.com/16845102/179880220-eda1608a-01de-4a71-9643-545ad608a244.png">

Here's what i see. Could you drag an image onto a comment below so I can see what you see? (literally drag the file onto the text area)

Best,
J

**Comment by JCBerger** [comment] 2022-07-20 15:32
<img width="1037" alt="Screen_Shot_2022-07-20_at_11_21_02_blurred" src="https://user-images.githubusercontent.com/3228462/180022113-aa8c6164-d066-4ed7-b185-1759a1552f5a.png">
I zoomed in to highlight an example and confirmed it had the Filemaker extension (.calc). Actually, I see the difference in yours as well. 

<img width="834" alt="Screen Shot 2022-07-20 at 11 29 52" src="https://user-images.githubusercontent.com/3228462/180022890-fedf14e7-5559-4cdb-839d-4faa909fcbdf.png">

Thanks for being so responsive and taking a look at this!

**Comment by jwillinghalpern** [comment] 2022-07-20 18:45
Gotcha. The expression in FM and it is indeed valid, and the highlighting looks consistent to me since every `\"` (a backslash-escaped double quotation mark) in the picture is the same color. The different color is highlighting escaped sequences:
<img width="586" alt="Screen Shot 2022-07-20 at 11 42 50 AM" src="https://user-images.githubusercontent.com/16845102/180058606-f6baf87a-3819-4a16-ade0-57042ed158c6.png">

Just curious, what result were you expecting instead? Did you anticipate them being the same color as the rest of the string (dark red in your case)?

**Comment by jwillinghalpern** [comment] 2022-07-26 18:50
I'm closing this but please reopen if you feel the issue is unresolved.

**Closed** 2022-07-26 18:50 UTC
